apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: rncp-k8s
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: rncp-k8s
type: Opaque
data:
  # "supersecret" encod√© en base64
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
